service: lambda-test-dev-hello
frameworkVersion: "3"
provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs16.x
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
functions:
  hello:
    handler: src/handler.hello
    name: lambda-test-${sls:stage}-hello # optional, Deployed Lambda name
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    events:
      - httpApi:
          path: /dev/test
          method: post
plugins:
  - serverless-offline
  - serverless-plugin-typescript
